# Generated by Django 5.0.4 on 2024-04-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_visa',
            field=models.BooleanField(blank=True, null=True, verbose_name='Visa'),
        ),
    ]
