# Generated by Django 5.0.4 on 2024-04-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, default='default_trip.png', upload_to='products/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
